### PR TITLE
Our intended destination is the WHATWG.

### PR DESCRIPTION
**Pull request by hober**

### CODE REVIEW

**Review by kewisch — APPROVED** [review]
I think this change looks good. While we could certainly consider going to WHATWG directly, using the CG allows for more flexibility while we document and align the current extensions model that is already implemented across browsers.

**Comment by dotproto** [comment]
I believe @cwilso expressed some concerns in our sync about WHATWG as there's some complexity on our side with creating new workstreams, but I confess I didn't completely track that exchange. I'll defer to him to clarify if necessary.

@kewisch, I agree in principal with using the CG to solidify process and seek alignment, but I hesitate on the reference to "the current extensions model". Just to be clear, are you referring to foundational concepts like isolated worlds for content scripts, the API surface area specified in the previous [draft CG report](https://browserext.github.io/browserext/) or something else?

**Comment by cwilso** [comment]
Yes.  First, I have concerns that this doesn't really match with the other workstreams of the WHATWG (which tend to be more infrastructural, and even further removed from UX).  Secondly, I suspect this will wave a red flag in front of the W3C's nose, which I don't think is necessary, and I'd rather just move it if it came to that.

**Comment by tantek** [comment]
@cwilso re: 
> Secondly, I suspect this will wave a red flag in front of the W3C's nose, which I don't think is necessary, and I'd rather just move it if it came to that.

I see the opposite. Declaring it up front sets expectations and reduces future likely conflict. Leaving it with an appearance of "to be decided" when the active participants have an intended desired destination opens it up to another opportunity for (some in) W3C to attempt to be territorial and start a fight over it.

**Comment by cwilso** [comment]
It's fine to have a difference of opinion on whether or not declaring it up front is a good idea or not, if the expectation is that it should go to the WHATWG.  However, see point 1: I think it fits even less well with the WHATWG than with the W3C.  Given that, I definitely don't think the charter should declare this.

**Comment by kewisch** [comment]
> @kewisch, I agree in principal with using the CG to solidify process and seek alignment, but I hesitate on the reference to "the current extensions model". Just to be clear, are you referring to foundational concepts like isolated worlds for content scripts, the API surface area specified in the previous [draft CG report](https://browserext.github.io/browserext/) or something else?
Yes, I was referring to the foundational concepts. With the extensions model I mean the core APIs, but also the fact that there are content scripts, there will be service workers, the manifest file itself, etc. I believe that in order to agree on what a future, standardized, extensions API and model will look like, we need to determine where exactly we differ and how we could align on that. It may not influence current manifest versions, but helps identify future roadmap for vendors and a path on getting closer in alignment.

**Pull request closed without merging**
