### PR TITLE
Add a Design Principles section.

### PR DESCRIPTION
**Pull request by hober**
Splitting #3 up into one PR per principle, so we can quickly land the uncontroversial ones, and have focused discussion on the others.

### CODE REVIEW

**Comment by hober** [comment]
Reviews very welcome, @kewisch @jessieberlin @dotproto @cwilso @tantek @MaheshKumarJha!

**Review by cwilso — APPROVED** [review]
This seems fine - certainly +1 on the TAG Design principles and Ethical Web principles.  I might suggest if we're not listing different principles, instead of saying "Our principles are inspired by..." just saying "This group intends to adgere to the..."

**Review by tantek — CHANGES_REQUESTED** [review]
Agree with @cwilso's thinking here. "inspired by ..." sounds like a preface to a new set of principles which I don't think is your intent. I like the "intends to adhere to" framing. 

Perhaps: s/Our principles are inspired by/This group adopts and intends to adhere to

and then after that if you need any particular principle is worth calling out, e.g. and providing a specific expansion in the context of this group, you could optionally do that as well (or in a later PR).

**Review by kewisch — APPROVED** [review]

**Comment by hober** [comment]
@cwilso wrote:

>> I might suggest if we're not listing different principles,

We will be. Remember, I'm splitting #3 into multiple PRs. This and #11 are just the first two.

>> instead of saying "Our principles are inspired by..." just saying "This group intends to adgere to the..."

I don't think that would make sense given we will be listing principles as in #3.

cc @tantek

**Comment by cwilso** [comment]
'K.

**Review by tantek — APPROVED** [review]
Thanks for the clarification of intent with this section and multiple pull requests. This LGTM as is.

**Pull request merged**
